# Generated by Django 3.2.23 on 2023-11-28 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_companyrec_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitcode', models.CharField(max_length=25)),
                ('details', models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='unitcode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.unitcode'),
            preserve_default=False,
        ),
    ]
