# Generated by Django 3.2.23 on 2023-11-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20231128_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='unitcode',
        ),
    ]
