# Generated by Django 3.2.23 on 2023-11-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_auto_20231128_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='coding',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.coding'),
            preserve_default=False,
        ),
    ]
