# Generated by Django 3.2.23 on 2023-11-29 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_auto_20231128_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
