# Generated by Django 3.2.23 on 2023-11-28 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contactperson', models.CharField(max_length=150)),
                ('contactnumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.companyrec'),
            preserve_default=False,
        ),
    ]
