# Generated by Django 3.2.23 on 2023-11-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20231128_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrec',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
