# Generated by Django 3.2.23 on 2023-11-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_delete_unitcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('details', models.CharField(max_length=125)),
            ],
        ),
    ]
