# Generated by Django 3.2.23 on 2023-11-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_unitcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding', models.CharField(max_length=50)),
                ('details', models.CharField(blank=True, max_length=125, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UnitCode',
        ),
    ]
