# Generated by Django 3.2.23 on 2023-11-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_alter_transaction_transdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='docnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
