# Generated by Django 3.2.23 on 2023-12-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_auto_20231211_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='qtyIN',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='qtyout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
